import { type Company } from '../../types';

const mural: Company = {
  name: 'Mural',
  logoUrl:
    'https://media.licdn.com/dms/image/C4E0BAQGQsTygnkEJnA/company-logo_200_200/0/1670343515708/muralco_logo?e=1727913600&v=beta&t=xnsv7cb7odNgr4gAc26d5QkYVrb067p_4j4AQso2H0Y',
  work: [
    {
      position: 'Senior Software Engineer',
      description: [
        'Implemented custom hit points in SVG shapes for easier diagramming',
        'Rewrote the arrows logic from scratch and reported bugs decresed to almost zero',
        'Replaced our text input tools for new ones in order to achieve coherence across all the application and allow for development of new features',
        'Worked with product to simplify the user experience of the application'
      ],
      from: new Date('2022-08-01')
    },
    {
      position: 'Software Engineer',
      description: [
        'Designed and developed the Infinite Canvas for our application which became a default way of creating murals',
        'Implemented the dot grid in the background so elements could easily be aligned',
        'Implemented support for rich text becoming for post it notes, then becoming the standard for all elements in the murals',
        'Lead list implementation for rich text elements'
      ],
      from: new Date('2020-06-01'),
      to: new Date('2022-07-01')
    },
    {
      position: 'Software Engineer',
      description: [
        'Developed an in house rendering engine using Canvas2D and Typescript with a special focus on performance, increasing frame rate from low 10s to low 40s in the worst case scenarios',
        'Developed testing rig for the rendering engine by comparing the expected render the result with the current one generated by the application in order to catch differences and the number of bugs this project had was pretty low',
        'Integrated the rendering engine into the main web application'
      ],
      from: new Date('2019-04-11'),
      to: new Date('2020-05-31')
    }
  ]
};

export const experienceData: Company[] = [mural];
